---
#TODO: this may not be needed in the future of apt_repository
- name: ensure pycurl is installed 
  apt: name=python-pycurl state=installed
  environment: zabbix_common_environment

- name: add zabbix.com key
  apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present
  environment: zabbix_common_environment

- name: add zabbix.com repo
  apt_repository: repo='deb http://repo.zabbix.com/zabbix/{{ zabbix_common_config_minor_version }}/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} main contrib non-free' state=present
  environment: zabbix_common_environment
