---
# This playbook runs all the common plays in the deployment

- name: install neccessary packages like net-tools, vim
  yum: name={{ item }} state=installed
  with_items:
    - net-tools
    - vim
    - git

- name: add group developer
  group: name=developer state=present

- name: add user zhangjinjie
  user: name={{ item }} state=present groups=developer password={{ my_password }} update_password=always generate_ssh_key=yes
  with_items:
    - zhangjinjie

- name: modify /etc/sudoers to add all privileges to developer group
  become: yes
  lineinfile: dest=/etc/sudoers state=present regexp='^%developer' line='%developer ALL=(ALL) NOPASSWD{{':'}} ALL'

- name: modify /etc/ssh/sshd_config to add zhangjinjie to AllowUsers section
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^(AllowUsers(?!.*\b{{ item }}\b).*)$'
    line: '\1 {{ item }}'
    backrefs: yes
  with_items:
    - zhangjinjie
  notify: restart sshd

- name: add static vpn route
  command: /usr/sbin/route add -net 10.8.0.0 netmask 255.255.255.0 gw 172.16.24.9
  ignore_errors: True

- name: add static vpn route to /etc/rc.local script
  lineinfile:
    dest: /etc/rc.local
    state: present
    regexp: '^route add -net 10\.8\.0\.0 netmask.*$'
    line: 'route add -net 10.8.0.0 netmask 255.255.255.0 gw 172.16.24.9'

- name: change hostname
  hostname: name={{ host_map[inventory_hostname] }}
  when: inventory_hostname in host_map

- name: make /etc/rc.local start at boot
  file: path=/etc/rc.d/rc.local mode=0755

- name: use aliyun yum repos
  copy: 
    src: '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.repo'
    dest: /etc/yum.repos.d/{{ ansible_distribution }}-Base.repo
    backup: yes
    mode: 0644

- name: install epel-release repo
  yum: name=epel-release state=installed

- name: disable epel.repo default
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 0
    backup: yes

- name: new /etc/pip.conf to add aliyum mirror to pip
  copy: src=pip.conf dest=/etc/pip.conf mode=0664

- name: install iptables-services for centos 7
  yum: name=iptables-services state=installed
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'

- name: turn off iptables
  service: name=iptables state=stopped 
  when: inventory_hostname not in skip_iptables_shutdown_servers

- name: clear iptables rules
  command: /sbin/iptables -F
  when: inventory_hostname not in skip_iptables_shutdown_servers
